shop/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/', views.cart_update, name='cart_update'),
    path('order/', views.OrderListView.as_view(), name='order_list'),
    path('order_create/', views.order_create, name='order_create'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
]

shop/catalog/urls.py
from django.urls import path

from .views import IndexView, WatchDetailView, WatchListView, FilterListView, SearchProductView, AddReview, AboutView

urlpatterns = [
    path('', IndexView.as_view(), name='index_page'),
    path('detail/<int:pk>/', WatchDetailView.as_view(), name='watch_detail'),
    path('product_list/', WatchListView.as_view(), name='product_list'),
    path('product_list/filter/', FilterListView.as_view(), name='filter'),
    path('product_list/search/', SearchProductView.as_view(), name='search'),
    path('add_review/<int:pk>/', AddReview.as_view(), name='add_review'),
    path('about/', AboutView.as_view(), name='about'),
]

shop/shop/urls.py
import allauth.account.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('accounts/', include('allauth.urls')),
    path('', include('catalog.urls')),
    path('cart/', include('cart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Watch Shop's Admin Panel"

shop/catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from django.utils import timezone


class Brand(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Брэнд'
        verbose_name_plural = 'Брэнды'


class Group(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Watch(models.Model):
    title = models.CharField(max_length=50, verbose_name='Модель')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='watchs', verbose_name='Брэнд')
    group = models.ManyToManyField(Group, related_name='watchs', verbose_name='Котегория')
    price = models.PositiveIntegerField(verbose_name='Цена')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='media', null=True, blank=True, verbose_name='Главное фото')
    create_at = models.DateTimeField(auto_now_add=True)

    def get_group(self):
        return ", ".join([str(p) for p in self.group.all()])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('watch_detail', args=[self.pk])

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Image(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    image = models.ImageField(upload_to='media', verbose_name='Изображение')
    product = models.ForeignKey(Watch, on_delete=models.CASCADE, related_name='images', verbose_name='Товар')


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField('Отзыв')
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, verbose_name='Родитель', blank=True, null=True
    )
    watch = models.ForeignKey(Watch, verbose_name='Товар', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.watch}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

shop/catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from catalog.models import Review


class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']

shop/catalog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.db.models import Q
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy, reverse
from django.views.generic.base import View

from .models import Watch, Group, Brand
from .forms import AddReviewForm


class FilterMixin:
    def get_categories(self):
        return Group.objects.all().order_by('name')

    def get_brands(self):
        return Brand.objects.all().order_by('name')

    def get_min_max_price(self):
        min_price = Watch.objects.order_by('price').first().price
        max_price = Watch.objects.order_by('-price').first().price
        return {'min': min_price, 'max': max_price}


class WatchCreateView(generic.CreateView):
    model = Watch
    fields = '__all__'
    template_name = 'catalog/watch_new.html'


class WatchUpdateView(generic.UpdateView):
    model = Watch
    fields = '__all__'
    template_name = 'catalog/watch_edit.html'


class WatchDeleteView(generic.DeleteView):
    model = Watch
    success_url = reverse_lazy('index_page')


class WatchListView(FilterMixin, generic.ListView):
    model = Watch
    template_name='catalog/product_list.html'

    paginate_by = 6


class WatchDetailView(generic.DetailView):
    model = Watch
    template_name = 'catalog/product_detail.html'


class IndexView(generic.ListView):
    model = Watch
    template_name = 'catalog/index.html'

    def get_queryset(self):
        return Watch.objects.all().order_by('-create_at')[:8]


class FilterListView(FilterMixin, generic.ListView):
    model = Watch
    template_name = 'catalog/product_list.html'

    # paginate_by = 1

    def get_queryset(self):
        categories = self.request.GET.getlist('category')
        brands = self.request.GET.getlist('brand')
        if categories and brands:
            queryset = Watch.objects.filter(
                Q(group__in=self.request.GET.getlist('category')),
                Q(brand__in=self.request.GET.getlist('brand'))
            ).distinct()
        else:
            queryset = Watch.objects.filter(
                Q(group__in=self.request.GET.getlist('category'))|
                Q(brand__in=self.request.GET.getlist('brand'))
            ).distinct()
        return queryset


class SearchProductView(FilterMixin, generic.ListView):
    model = Watch
    template_name = 'catalog/product_list.html'

    def get_queryset(self):
        return Watch.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context


class AddReview(View):
    def post(self, request, pk):
        form = AddReviewForm(request.POST)
        watch = Watch.objects.get(pk=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.watch = watch
            form.user = request.user
            form.save()
        return redirect(watch.get_absolute_url())


class AboutView(View):
    def get(self, request):
        return render(request, 'catalog/about.html')

shop/catalog/templates/catalog/about.html
{% extends 'base.html' %}

{% load static %}


{% block content %}

	<!-- Title Page -->
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url({% static 'catalog/images/heading-pages-06.jpg' %});">
		<h2 class="l-text2 t-center">
			About
		</h2>
	</section>

	<!-- content page -->
	<section class="bgwhite p-t-66 p-b-38">
		<div class="container">
			<div class="row">
				<div class="col-md-4 p-b-30">
					<div class="hov-img-zoom">
						<img src="{% static 'catalog/images/banner-14.jpg' %}" alt="IMG-ABOUT">
					</div>
				</div>

				<div class="col-md-8 p-b-30">
					<h3 class="m-text26 p-t-15 p-b-16">
						Our story
					</h3>

					<p class="p-b-28">
						Phasellus egestas nisi nisi, lobortis ultricies risus semper nec. Vestibulum pharetra ac ante ut pellentesque. Curabitur fringilla dolor quis lorem accumsan, vitae molestie urna dapibus. Pellentesque porta est ac neque bibendum viverra. Vivamus lobortis magna ut interdum laoreet. Donec gravida lorem elit, quis condimentum ex semper sit amet. Fusce eget ligula magna. Aliquam aliquam imperdiet sodales. Ut fringilla turpis in vehicula vehicula. Pellentesque congue ac orci ut gravida. Aliquam erat volutpat. Donec iaculis lectus a arcu facilisis, eu sodales lectus sagittis. Etiam pellentesque, magna vel dictum rutrum, neque justo eleifend elit, vel tincidunt erat arcu ut sem. Sed rutrum, turpis ut commodo efficitur, quam velit convallis ipsum, et maximus enim ligula ac ligula. Vivamus tristique vulputate ultricies. Sed vitae ultrices orci.
					</p>

					<div class="bo13 p-l-29 m-l-9 p-b-10">
						<p class="p-b-11">
							Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while.
						</p>

						<span class="s-text7">
							- Steve Job’s
						</span>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock content %}


shop/catalog/templates/catalog/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
	<!-- Slide1 -->
	<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">
				<div class="item-slick1 item1-slick1" style="background-image: url({% static 'catalog/images/master-slide-02.jpg' %});">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="fadeInDown">
							Women Collection 2018
						</span>

						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="fadeInUp">
							New arrivals
						</h2>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
							<!-- Button -->
							<a href="{% url 'product_list' %}" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
								Shop Now
							</a>
						</div>
					</div>
				</div>

				<div class="item-slick1 item2-slick1" style="background-image: url({% static 'catalog/images/master-slide-03.jpg' %});">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="rollIn">
							Women Collection 2018
						</span>

						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="lightSpeedIn">
							New arrivals
						</h2>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="slideInUp">
							<!-- Button -->
							<a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
								Shop Now
							</a>
						</div>
					</div>
				</div>

				<div class="item-slick1 item3-slick1" style="background-image: url({% static 'catalog/images/master-slide-04.jpg' %});">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="rotateInDownLeft">
							Women Collection 2018
						</span>

						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="rotateInUpRight">
							New arrivals
						</h2>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="rotateIn">
							<!-- Button -->
							<a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
								Shop Now
							</a>
						</div>
					</div>
				</div>

			</div>
		</div>
	</section>

	<!-- New Product -->
	<section class="newproduct bgwhite p-t-45 p-b-105">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Featured Products
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">
					{% for watch in object_list %}
					<div class="item-slick2 p-l-15 p-r-15">
						<!-- Block2 -->
						<div class="block2">
							<div class="wrap-pic-w of-hidden pos-relative block2-labelnew">

								<img src="{% if watch.image %} {{ watch.image.url }}
								{% else %}block2-img{% static 'catalog/images/item-02.jpg' %}{% endif %}" alt="IMG-PRODUCT">

								<div class="block2-overlay trans-0-4">

									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
											Add to Cart
										</button>
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{% url 'watch_detail' watch.pk %}" class="block2-name dis-block s-text3 p-b-5">
									{{ watch }}
								</a>

								<span class="block2-price m-text6 p-r-5">
									{{ watch.price }} сом
								</span>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
			</div>

		</div>
	</section>

	{% endblock content %}


</body>
</html>

shop/catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<!-- breadcrumb -->
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
    <a href="{% url 'index_page' %}" class="s-text16">
        Home
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <a href="#" class="s-text16">
        {{ watch.brand }}
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <span class="s-text17">
			{{ watch }}
		</span>
</div>

<!-- Product Detail -->
<div class="container bgwhite p-t-35 p-b-80">
    <div class="flex-w flex-sb">
        <div class="w-size13 p-t-30 respon5">
            <div class="wrap-slick3 flex-sb flex-w">
                <div class="wrap-slick3-dots"></div>

                <div class="slick3">
                    <div class="item-slick3" data-thumb="{{ watch.image.url }}">
                        <div class="wrap-pic-w">
                            <img src="{{ watch.image.url }}" alt="IMG-PRODUCT">
                        </div>
                    </div>
                    {% for img in watch.images.all %}
                    <div class="item-slick3" data-thumb="{{ img.image.url }}">
                        <div class="wrap-pic-w">
                            <img src="{{ img.image.url }}" alt="{{ img.title }}">
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="w-size14 p-t-30 respon5">
            <h4 class="product-detail-name m-text16 p-b-13">
                {{ watch }}
            </h4>

            <span class="m-text17">
					{{ watch.price }} сом
				</span>

            <!--  -->
            <div class="p-t-33 p-b-60">
                <div class="flex-r-m flex-w p-t-10">
                    <div class="w-size16 flex-m flex-w">
                        <form id="add_cart" action="{% url 'cart_add' watch.id %}" method="post">
                            {% csrf_token %}
                        <div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">

                            <button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
                                <i class="fs-12 fa fa-minus" aria-hidden="true"></i>
                            </button>

                            <input class="size8 m-text18 t-center num-product" type="number" name="quantity"
                                   value="1">

                            <button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
                                <i class="fs-12 fa fa-plus" aria-hidden="true"></i>
                            </button>
                        </div>
                        </form>
                        <div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10">
                            <!-- Button -->
                            <button type="submit" form="add_cart" class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                                Add to Cart
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="p-b-45">
                <span class="s-text8 m-r-35">Brand: {{ watch.brand }}</span>
                <span class="s-text8">Categories: {{ watch.get_group }}</span>
            </div>

            <!--  -->
            <div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
                <h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
                    Description
                    <i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
                    <i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
                </h5>

                <div class="dropdown-content dis-none p-t-15 p-b-23">
                    <p class="s-text8">
                        {{ watch.description }}
                    </p>
                </div>
            </div>

            <div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
                <h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
                    Reviews ({{ watch.review_set.all.count }})
                    <i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
                    <i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
                </h5>

                <div class="dropdown-content dis-none p-t-15 p-b-23">

                    {% for review in watch.review_set.all %}
                    <div class="media py-1">
                        <div class="media-body mt-4">
                            <h6 class="mt-0 editContent m-text19">
                                {{ review.user.username }}
                            </h6>
                            <p class="mt-2 editContent s-text8">
                                {{ review.text }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                    {% if user.is_authenticated %}
                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h5 class="editContent" style="outline: none; cursor: inherit;">
                                    Оставить отзыв
                                </h5>
                                <form action="{% url 'add_review' watch.pk %}" method="post" class="mt-4">
                                    {% csrf_token %}
                                    <div class="form-group editContent">
                                        <label for="contactcomment" class="editContent">
                                            Ваш комментарий *
                                        </label>
                                        <textarea class="form-control border" rows="5" name="text"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3">
                                        Отправить
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>

{% endblock content %}

shop/catalog/templates/catalog/product_list.html
{% extends 'base.html' %}

{% load static %}


{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'catalog/vendor/noui/nouislider.min.css' %}">
{% endblock css %}


{% block content %}




	<!-- Title Page -->
	<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url({% static 'catalog/images/heading-pages-02.jpg' %});">
		<h2 class="l-text2 t-center">
			Women
		</h2>
		<p class="m-text13 t-center">
			New Arrivals Women Collection 2018
		</p>
	</section>


	<!-- Content page -->
	<section class="bgwhite p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar p-r-20 p-r-0-sm">
						<!--  -->
						<form action="{% url 'filter' %}" method="get">
							<h4 class="m-text14 p-b-7">
								Categories
							</h4>

							<ul class="p-b-54">
								{% for category in view.get_categories %}
								<li class="p-t-4">
									<input type="checkbox" name="category" value="{{ category.pk }}">
									<span class="s-text13 active1">{{ category }}</span>
								</li>
								{% endfor %}
							</ul>

							<!--  -->
							<h4 class="m-text14 p-b-32">
								Brands
							</h4>

							<ul class="p-b-54">
								{% for brand in view.get_brands %}
								<li class="p-t-4">
									<input type="checkbox" name="brand" value="{{ brand.pk }}">
									<span class="s-text13 active1">{{ brand }}</span>
								</li>
								{% endfor %}
							</ul>
							<button type="submit" class="flex-c-m size4 bg7 bo-rad-15 hov1 s-text14 trans-0-4">
										Filter
							</button>
						</form>

						<div class="filter-price p-t-22 p-b-50 bo3">
							<div class="m-text15 p-b-17">
								Price
							</div>

							<div class="wra-filter-bar">
								<div id="filter-bar"></div>
							</div>

							<div class="flex-sb-m flex-w p-t-16">
<!--								<div class="w-size11">-->
<!--									&lt;!&ndash; Button &ndash;&gt;-->
<!--									<button class="flex-c-m size4 bg7 bo-rad-15 hov1 s-text14 trans-0-4">-->
<!--										Filter-->
<!--									</button>-->
<!--								</div>-->



								<div class="s-text3 p-t-10 p-b-10">
									Range: $<span id="value-lower">{{ view.get_min_max_price.min }}</span> - $<span id="value-upper">{{ view.get_min_max_price.max }}</span>
								</div>
							</div>
						</div>

						<div class="search-product pos-relative bo4 of-hidden">
							<form action="{% url 'search' %}" method="get">
								<input class="s-text7 size6 p-l-23 p-r-50" type="text" name="q" placeholder="Search Products...">

								<button type="submit" class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
									<i class="fs-12 fa fa-search" aria-hidden="true"></i>
								</button>
							</form>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
					<!--  -->
					<div class="flex-sb-m flex-w p-b-35">
						<div class="flex-w">
							<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10">
								<select class="selection-2" name="sorting">
									<option>Default Sorting</option>
									<option>Popularity</option>
									<option>Price: low to high</option>
									<option>Price: high to low</option>
								</select>
							</div>

							<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10">
								<select class="selection-2" name="sorting">
									<option>Price</option>
									<option>$0.00 - $50.00</option>
									<option>$50.00 - $100.00</option>
									<option>$100.00 - $150.00</option>
									<option>$150.00 - $200.00</option>
									<option>$200.00+</option>

								</select>
							</div>
						</div>
					</div>

					<!-- Product -->
					<div class="row">

						{% for watch in object_list %}
						<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
							<!-- Block2 -->
							<div class="block2">
								<div class="block2-img wrap-pic-w of-hidden pos-relative">
									<img src="{{ watch.image.url }}" alt="IMG-PRODUCT">

									<div class="block2-overlay trans-0-4">
										<div class="block2-btn-addcart w-size1 trans-0-4">
											<!-- Button -->
											<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
												Add to Cart
											</button>
										</div>
									</div>
								</div>

								<div class="block2-txt p-t-20">
									<a href="{% url 'watch_detail' watch.pk %}" class="block2-name dis-block s-text3 p-b-5">
										{{ watch }}
									</a>

									<span class="block2-price m-text6 p-r-5">
										{{ watch.price }} сом
									</span>
								</div>
							</div>
						</div>

						{% endfor %}

					</div>

					<!-- Pagination -->
					<div class="pagination flex-m flex-w p-t-26">
<!--						<a href="#" class="item-pagination flex-c-m trans-0-4 active-pagination">1</a>-->
<!--						<a href="#" class="item-pagination flex-c-m trans-0-4">2</a>-->
						{% include 'catalog/includes/pagination.html' %}
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock content %}

{% block script %}

<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/bootstrap/js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'catalog/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/select2/select2.min.js' %}"></script>
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});

		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect2')
		});
	</script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/daterangepicker/moment.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'catalog/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/slick/slick.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'catalog/js/slick-custom.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/sweetalert/sweetalert.min.js' %}"></script>
	<script type="text/javascript">
		$('.block2-btn-addcart').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to cart !", "success");
			});
		});

		$('.block2-btn-addwishlist').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");
			});
		});
	</script>

<!--===============================================================================================-->
	<script type="text/javascript" src="{% static 'catalog/vendor/noui/nouislider.min.js' %}"></script>
	<script type="text/javascript">
		/*[ No ui ]
	    ===========================================================*/
	    var filterBar = document.getElementById('filter-bar');

	    noUiSlider.create(filterBar, {
	        start: [ 50, 200 ],
	        connect: true,
	        range: {
	            'min': 50,
	            'max': 200
	        }
	    });

	    var skipValues = [
	    document.getElementById('value-lower'),
	    document.getElementById('value-upper')
	    ];

	    filterBar.noUiSlider.on('update', function( values, handle ) {
	        skipValues[handle].innerHTML = Math.round(values[handle]) ;
	    });
	</script>
<!--===============================================================================================-->
	<script src="{% static 'catalog/js/main.js' %}"></script>
{% endblock script %}

shop/catalog/templates/catalog/test.html
123
{% for watch in object_list %}
<li>
    <p>{{ watch }}</p>
    <p>{{ watch.brand }}</p>
    <p>{{ watch.price }}</p>
    <p>{{ watch.description }}</p>
</li>

{% endfor %}